### ISSUE TITLE
Duplexify exception

### ISSUE THREAD

**Issue by Unitech** [mafintosh/ssh-exec#24]
When running this script (with a fresh install, duplexify@3.4.3):

``` javascript
var sshExec = require('ssh-exec');

sshExec('ls -l', {
  host : 'xxx.xxx.xxx.xxx',
  user : 'root'
});
```

I get this exception from duplexify:

```
/home/unitech/gridcontrol/gridcontrol/grid-cli/node_modules/duplexify/index.js:161
  while ((data = this._readable2.read(state.buffer.length ? state.buffer[0].length : state.length)) !== null) {
                                                                           ^
TypeError: Cannot read property 'length' of undefined
    at Duplexify._forward (/home/unitech/gridcontrol/gridcontrol/grid-cli/node_modules/duplexify/index.js:161:76)
    at Channel.onreadable (/home/unitech/gridcontrol/gridcontrol/grid-cli/node_modules/duplexify/index.js:126:10)
    at emitNone (events.js:86:13)
    at Channel.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:433:10)
    at emitReadable (_stream_readable.js:427:7)
    at readableAddChunk (_stream_readable.js:188:13)
    at Channel.Readable.push (_stream_readable.js:135:10)
    at SSH2Stream.<anonymous> (/home/unitech/gridcontrol/gridcontrol/grid-cli/node_modules/ssh2/lib/Channel.js:146:15)
    at emitOne (events.js:96:13)
```

**Comment by mafintosh** [comment]
Hmm. Fresh install should fetch latest duplexify 3.4.5 that fixes this. Are you you arent using a cache or something?

**Comment by Unitech** [comment]
great, just run a `npm cache clear` it works now,

Thank you!
Closing
